### ISSUE TITLE
segmentation fault on Context.run() with no queries

### ISSUE THREAD

**Issue by dkg** [getdnsapi/getdns-python-bindings#27]
The following python script produces a segmentation fault with libgetdns 0.2.0 and python-getdns 0.3.1:

```python
#!/usr/bin/env python
import getdns
ctx = getdns.Context()
ctx.run()
```

**Comment by MelindaShore** [comment]
Added a null pointer check to context_run(), in the develop branch.  Please confirm that it works correctly for you.

**Comment by dkg** [comment]
On Wed 2015-06-17 11:58:25 -0400, Melinda Shore wrote:
> Added a null pointer check to context_run(), in the develop branch.  Please confirm that it works correctly for you.

Yep, 5e45f2ace0e515a172706fb94fdebd71fefd6e01 fixes the problem for me.

Attached is a backport of it against 0.3.1.

Thanks,

        --dkg
