### ISSUE TITLE
Pip downloads old version from pypi, version schema change

### ISSUE THREAD

**Issue by teprrr** [getdnsapi/getdns-python-bindings#44]
Using pip to install getdns package installs version 0.6.1 instead of the newest 1.0b, caused by different naming scheme I suppose:

getdns-v1.0beta.tar.gz
getdns-0.6.1.tar.gz

Is this wanted behavior in this case?

**Comment by MelindaShore** [comment]
No, it's definitely unwanted behavior!  I've remedied the problem - thanks for bringing it to my attention.
